FROM node:20-alpine

ARG APP_FOLDER=nodejs

WORKDIR /app

COPY ${APP_FOLDER}/package*.json ./
RUN npm install --production

COPY ${APP_FOLDER}/ .

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

CMD ["npm", "start"]